var plenariesData = {
    "padden": {
        "name": "Carol Padden",
        "title": "Why are sign languages iconic?",
        "url": "http://communication.ucsd.edu/people/faculty/carol-padden.html",
        "affiliation1": "Professor of Communication\nCenter for Research in Language, Human Development, Education Studies\nUniversity of California San Diego",
        "affiliation2": "",
        "about": "Carol Padden studies structural properties of large national sign languages and newly emerging sign languages including in a community of Bedouins in southern Israel. Her work explores how language emerges and becomes a community sign language as it is transmitted across generations.  Her larger goal is to understand the multimodal basis of human communication, and the range of expressive forms in languages around the world, from spoken languages to gesture to sign languages. ",
        "abstract": "The standard answer to this question is that sign languages are iconic because they can be, as visual-manual systems. But to ask why they are iconic means to ask why they need to be. Knowing that sign languages are iconic does not explain how iconicity works, nor how it works in other manual visual systems that are not sign languages, such as in fingerspelling or in auxiliary sign languages such as Walpiri Sign Language which is used among widows in the central desert region of Australia. In this talk, I compare sign languages to different visual-manual systems that have been described in the literature. Deaf community sign languages or deaf sign languages constitute one group, though both terms are problematic because they suggest that deaf people are the exclusive developers of or the primary users of sign languages which is not always true. Hearing people play a much larger role in the creation and propagation of sign languages than has been described in the literature. Sign languages are largely metonymic systems. Manual alphabetic systems that accompany sign languages too are iconic, but characteristically of the written characters themselves, not of referents. Finally, Walpiri Sign Language is called an \u201cauxiliary\u201d system because it is produced in close relationship with a spoken language, in this case, Walpiri. As it is used among hearing (silent) speakers of Walpiri, it appears that its iconicity is of a yet different type. Why are there different types? I argue that the differences in iconicity demonstrate that iconicity is not an independent property of language but is constituted by it. In other words, iconicity and grammar are co-constitutive. I further show, using data from a young sign language used by Bedouins in Israel that, like grammar, iconicity is not immediately available to human language but takes time to emerge in a community of users. ",
        "image": "padden.jpg",
        "date": "Wednesday, April 15, 2020",
        "time": "09:30",
        "location": "Aula QA (VUB)"
    },
    "vernes": {
        "name": "Sonja C. Vernes",
        "title": "Understanding Bat Vocal Learning to Gain Insight Into Speech and Language",
        "url": "https://www.mpi.nl/people/vernes-sonja",
        "affiliation1": "Max Planck Research Group Leader\nNeurogenetics of Vocal Communication Group\nMax Planck Institute for Psycholinguistics, Nijmegen",
        "affiliation2": "Affiliated Principal Investigator\nDonders Institute for Brain, Cognition and Behaviour",
        "about": "Sonja Vernes investigates vocal learning in bats to understand the biology and evolution of this trait using cross-disciplinary approaches spanning genetics and genomics, neurobiology, and behaviour. She places these findings in a comparative context to shed light on the shared properties of mammalian vocal learning and ultimately, human speech and language.",
        "abstract": "The comparative approach can provide insight into the evolution of speech, language, and social communication by studying relevant traits in animal systems. Bats are emerging as a model system with great potential to shed light on these processes given their learned vocalisations, close social interactions, and mammalian physiology. Bats are highly social animals that have developed sophisticated vocal and auditory systems for navigation and communication. Furthermore, their small size, amenability to manipulation, and the rich history of studying the neuroethological of echolocation in bats, makes them an excellent system to model the biology underlying vocal learning behaviour. I will discuss the evidence for vocal learning in bats. This encompasses our understanding of the abilities bats have displayed for vocal learning, what is known about the timing and social structure needed for such learning, and current knowledge about the prevalence of the trait across the order. I will highlight approaches being undertaken to understand the neurobiological and genetic mechanisms underlying this complex behaviour, and raise some key questions that should be answered to advance our understanding of the biological encoding and evolution of speech and spoken communication.",
        "image": "vernes.jpg",
        "date": "Thursday, April 16, 2020",
        "time": "09:00",
        "location": "Aula QA (VUB)"
    },
    "schouwstra": {
        "name": "Marieke Schouwstra",
        "title": "Improvisation: A Fundamental Process in Language Emergence",
        "url": "https://mariekeschouwstra.github.io/",
        "affiliation1": "Postdoctoral researcher\nCentre for Language Evolution\nSchool of Philosophy, Psychology and Language Sciences\nUniversity of Edinburgh",
        "affiliation2": "",
        "about": "Marieke Schouwstra studies the emergence of linguistic structure by conducting laboratory experiments in which participants develop artificial sign languages from scratch. She focuses on the role of semantic properties in improvisation, interaction, and iterated learning, and compares her laboratory results to real world data by looking at observations from old and new sign languages. ",
        "abstract": "All languages have systematic structure, allowing us to communicate an unbounded number of thoughts. Among those who study where this structure comes from, there is increasing recognition that both individual and cultural processes play a role in the evolution of language. But it is not clear how these processes interact. My research tackles this issue by focusing on what happens when languages are created anew. I do this by conducting laboratory experiments in which naive participants improvise to communicate in novel ways, and by comparing my lab results to actual cases of recent language emergence, for example Nicaraguan Sign Language.\n\nOne way to elicit improvised utterances is by using silent gesture: participants use their hands and bodies but no speech to convey information. This method has been applied successfully in studies of Basic Word Order, as a way to uncover individual (largely native-language-independent) biases for structuring information about transitive events. In my work I combine silent gesture with experimental techniques from language evolution more broadly, to see what happens to the results of improvisation under the influence of communicative interaction and iterated learning.\n\nA key finding has been that laboratory participants, when they improvise, use structures that are shaped by the semantic properties of the message to be conveyed. The structure of their utterances reflects the way in which they conceptualise the world. I call this tendency naturalness, and show that naturalness, together with iconicity, is an effective bias to get a novel communication system off the ground. However, my experiments show that when multiple utterances are produced and perceived in communicative interaction and when language is transmitted to new generations, this brings new biases to the fore, replacing the biases dominant in improvisation.\n\nIn this talk, I will review experimental evidence from different linguistic domains, for instance, Basic Word Order, Noun Phrase structure, and the structure of the lexicon, and give an overview of the biases we observed in improvisation, communicative interaction, and iterated learning.\n\nObserving the birth of linguistic systems in the laboratory is exciting and informative, but it is important to recognise that the idealised setting of the laboratory might miss crucial factors that are important in shaping real emerging languages. Because of this I will discuss ongoing work in which we compare laboratory results concerning basic word order to sentence structures from a young sign language.",
        "image": "schouwstra.jpg",
        "date": "Thursday, April 16, 2020",
        "time": "17:00",
        "location": "Aula QA (VUB)"
    },
    "tehrani": {
        "name": "Jamie Tehrani",
        "title": "Oral Traditions and Language Evolution: The Plot Thickens",
        "url": "https://www.dur.ac.uk/anthropology/staff/profile/?id=5388",
        "affiliation1": "Associate Professor of Anthropology\nDurham Cultural Evolution Research Centre (DCEC)\nDepartment of Anthropology\nDurham University",
        "affiliation2": "",
        "about": "Jamie Tehrani is an anthropologist whose work focuses on the transmission and evolution of cultural traditions. He is especially interested in understanding how and why certain narratives - such as myths, fairy tales and urban legends - spread within and between populations, and get passed down from generation to generation. His research into these questions uses data from the international folklore record, human population genetics and historical linguistics, and a variety of methodologies, including iterated learning experiments and comparative phylogenetic analysis.",
        "abstract": "In this talk I will explore the numerous points of contact that exist between studies of language evolution and the transmission of oral traditions, such as folktales, myths and legends. These connections have deep and tangled historical roots, from the work of nineteenth century writers like Augustus Schleicher and the Brothers Grimm, who attempted to reconstruct Proto-Indo-European language and folklore, to Frederic Bartlett\u2019s pioneering studies of folktale transmission that helped establish the iterated learning paradigm so widely used in modern-day experimental studies of language evolution. While the two fields grew apart in the latter half of the twentieth century, the emergence of Cultural Evolution has opened up new possibilities for cross-fertilisation. I will discuss the possibilities and prospects for developing these synergies by presenting a series of case studies on issues of mutual interest, including the role of transmission biases/ factors of attraction, cultural diffusion and population histories, and the relationship between demography and cultural complexity.",
        "image": "tehrani.jpg",
        "date": "Friday, April 17, 2020",
        "time": "09:00",
        "location": "Aula QA (VUB)"
    }
}
